/**
 * @file index.ts
 * @description Main entry point for shared type definitions used across Frontend and Backend.
 * @module packages.shared-types.src
 *
 * @responsibility
 * - Exports all Zod schemas and TypeScript types used across the monorepo
 * - Acts as the Single Source of Truth for API contracts and Data Models
 * - Categorizes types into Canvas, Task, Model, and Pipeline domains
 *
 * @exports
 * - *Schema: Zod schemas for runtime validation
 * - type *: TypeScript type definitions inferred from Zod
 */

// Canvas types + constants (single source of truth)
export {
  TIMELINE_DSL_CATEGORY_ALLOWED_ITEM_TYPES,
  TIMELINE_DSL_FIELD_ANNOTATIONS,
  TIMELINE_DSL_FIELD_CATALOG,
  TIMELINE_DSL_ROLE_ALLOWED_ITEM_TYPES,
  TIMELINE_DSL_ROLE_CATEGORIES,
  TIMELINE_DSL_RUNTIME_CONSUMERS,
  TIMELINE_DSL_TRACK_ROLES,
  TIMELINE_CLIP_ANIMATION_TYPES,
  TIMELINE_CAPTION_POSITIONS,
  TIMELINE_COMPOSITION_KINDS,
  TIMELINE_COMPOSITION_RUNTIMES,
  TIMELINE_DERIVED_MEDIA_TYPES,
  TIMELINE_DERIVATION_KINDS,
  TIMELINE_MEDIA_FITS,
  TIMELINE_ITEM_TRANSFORM_SEMANTICS,
  TIMELINE_TEXT_ALIGNMENTS,
  TIMELINE_TRANSITION_TYPES,
  timelineDslAnnotatedObjectShape,
  TimelineAudioDuckingSchema,
  TimelineCaptionCueSchema,
  TimelineCaptionWordReferenceSchema,
  TimelineClipAnimationSchema,
  TimelineDerivedAssetSchema,
  TimelineEditorAssetTranscriptSchema,
  TimelineEditorTranscriptWordSchema,
  TimelineEffectInstanceRefSchema,
  TimelineEffectParamValueSchema,
  TimelineItemPropertiesSchema,
  TimelineMediaAssetRefSchema,
  TimelineMediaFitSchema,
  TimelineSourceToOutputFrameMapSchema,
  TimelineSequenceSchema,
  TimelineTypographyStyleSchema,
  type TimelineDslEditorSurface,
  type TimelineDslFieldAnnotation,
  type TimelineDslFieldRequiredness,
  type TimelineDslItemType,
  type TimelineDslRuntimeConsumer,
  type TimelineDslTrackCategory,
  type TimelineDslTrackRole,
} from './timeline-field-annotations';

export {
  TIMELINE_OPERATION_CATALOG,
  TIMELINE_OPERATION_REGISTRY,
  type TimelineAgentOperationId,
  type TimelineEditorActionId,
  type TimelineEditorCommandId,
  type TimelineOperationAccess,
  type TimelineOperationAnnotation,
  type TimelineOperationCas,
  type TimelineOperationCatalogEntry,
  type TimelineOperationId,
  type TimelineOperationKind,
  type TimelineOperationReadProof,
} from './timeline-operation-annotations';

export {
  AgentAnnotationDraftSchema,
  AgentAnnotationPromptPayloadSchema,
  AgentAnnotationSelectionSchema,
  AgentAnnotationSurfaceSchema,
  AgentAnnotationTargetSchema,
  AgentAnnotationVisualRectSchema,
  serializeAgentAnnotationPromptBlock,
  type AgentAnnotationDraft,
  type AgentAnnotationObjectRef,
  type AgentAnnotationPromptPayload,
  type AgentAnnotationSelection,
  type AgentAnnotationSurface,
  type AgentAnnotationTarget,
  type AgentAnnotationVisualRect,
} from './agent-annotation';

export {
  TIMELINE_LIBRARY_CATEGORIES,
  TIMELINE_LIBRARY_CATEGORY_CONTRACTS,
  TIMELINE_LIBRARY_GROUPS,
  TimelineLibraryCollectionSchema,
  TimelineLibraryItemSchema,
  TimelineLibraryItemViewStateSchema,
  TimelineLibraryProvenanceSchema,
  getTimelineLibraryCategoryContract,
  parseTimelineLibraryItem,
  type TimelineLibraryCategoryContract,
  type TimelineLibraryCategory,
  type TimelineLibraryCollection,
  type TimelineLibraryGroup,
  type TimelineLibraryItem,
  type TimelineLibraryItemViewState,
} from './timeline-library';

export {
  BuildTimelineTranscriptProjectionInputSchema,
  TimelineTranscriptClipInputSchema,
  TimelineTranscriptProjectionSchema,
  TimelineTranscriptSourceSchema,
  TimelineTranscriptWordSchema,
  buildTimelineTranscriptProjection,
  type BuildTimelineTranscriptProjectionInput,
  type TimelineTranscriptClipInput,
  type TimelineTranscriptProjection,
  type TimelineTranscriptSource,
  type TimelineTranscriptWord,
} from './timeline-transcript';

export {
  DirectorStageActionClipSchema,
  DirectorStageActionLayerSchema,
  DirectorStageActionNameSchema,
  DirectorStageAttachmentSchema,
  DirectorStageAttachmentSocketSchema,
  DirectorStageAnimationKeyframeSchema,
  DirectorStageAnimationTrackSchema,
  DirectorStageAspectRatioSchema,
  DirectorStageCameraSchema,
  DirectorStageCameraRigLensSchema,
  DirectorStageCameraRigOrientationSchema,
  DirectorStageCameraRigPathSchema,
  DirectorStageCameraRigSchema,
  DirectorStageCameraCueSchema,
  DirectorStageEnvironmentCalibrationSchema,
  DirectorStageObjectSchema,
  DirectorStagePoseSchema,
  DirectorStageShotSchema,
  DirectorStageShotCompositionSchema,
  DirectorStageSequenceShotSchema,
  DirectorStageMotionAssetSchema,
  DirectorStageSignedAxisSchema,
  DirectorStageStateSchema,
  DirectorStageStoryBeatSchema,
  DirectorStageTransformSchema,
  DirectorStageVector3Schema,
  DirectorStageWorkingVolumePresetSchema,
  DirectorStageWorkingVolumeSchema,
  applyDirectorStageCommand,
  attachDirectorStageToCanvas,
  createDefaultDirectorStageState,
  directorDefaultAttachmentOffset,
  createProjectDirectorStage,
  detachDirectorStageFromCanvas,
  directorStageJsonSchema,
  listProjectDirectorStages,
  projectDirectorStageReadToken,
  projectDirectorStageRevisionId,
  reconcileProjectDirectorStageOwnership,
  readProjectDirectorStage,
  updateProjectDirectorStageState,
  type ApplyDirectorStageCommandResult,
  type DirectorStageActionClip,
  type DirectorStageActionLayer,
  type DirectorStageActionName,
  type DirectorStageAttachment,
  type DirectorStageAttachmentSocket,
  type DirectorStageCamera,
  type DirectorStageCameraRig,
  type DirectorStageCameraCue,
  type DirectorStageCameraPatch,
  type DirectorStageCommand,
  type DirectorStageEnvironmentCalibration,
  type DirectorStageObject,
  type DirectorStageObjectPatch,
  type DirectorStageOwner,
  type DirectorStageShot,
  type DirectorStageShotComposition,
  type DirectorStageSequenceShot,
  type DirectorStageSchemaContract,
  type DirectorStageMotionAsset,
  type DirectorStageState,
  type DirectorStageStoryBeat,
  type DirectorStageTransform,
  type DirectorStageVector3,
  type DirectorStageWorkingVolume,
  type DirectorStageWorkingVolumePreset,
  type ProjectDirectorStage,
  type ProjectDirectorStageMutationResult,
  type DirectorStageOwnershipReconciliation,
} from './director-stage';

export {
  DirectorReferencePacketSchema,
  DirectorReferenceShotSchema,
  DirectorReferenceStillSchema,
  DirectorReferenceVideoSchema,
  createDirectorReferencePacket,
  type CreateDirectorReferencePacketInput,
  type DirectorReferencePacket,
  type DirectorReferenceShot,
  type DirectorReferenceStill,
  type DirectorReferenceVideo,
} from './director-reference';

export {
  // Schemas
  PositionSchema,
  NodeStatusSchema,
  NodeDataSchema,
  CanvasNodeSchema,
  CanvasEdgeSchema,
  LoroDocumentStateSchema,
  NodeInfoSchema,
  EdgeInfoSchema,
  ProjectContextSchema,
  // ReactFlow types
  RF_NODE_TYPE,
  ACTION_TYPE,
  EDIT_KIND,
  AGENT_NODE_TYPE_MAP,
  // Edit-node param schemas
  CropRectSchema,
  ImageEditParamsSchema,
  VideoClipParamsSchema,
  // Agent-facing types
  NodeType,
  ALL_NODE_TYPES,
  CONTENT_NODE_TYPES,
  GENERATION_NODE_TYPES,
  isGenerationNodeType,
  FrontendNodeType,
  ProposalType,
  TaskStatus,
  AssetStatus,
  // Custom actions
  ACTION_PROVIDER_PRESETS,
  ACTION_PROVIDER_IDS,
  ActionProviderIdSchema,
  ActionProviderRefSchema,
  CustomActionModelSchema,
  CustomActionParameterSchema,
  CustomActionSecretSchema,
  CustomActionDefinitionSchema,
  normalizeActionProviderId,
  mergeActionProviderSecrets,
  isCustomActionType,
  getCustomActionId,
  // Validation & Builders
  validateGenerationInput,
  buildPendingAssetNode,
  buildGenerationPayload,
  customActionDefaultParams,
  extractLabelFromPrompt,
  type GenerationConfig,
  // TypeScript types
  type Position,
  type NodeStatus,
  type NodeData,
  type CanvasNode,
  type CanvasEdge,
  type LoroDocumentState,
  type ValidateGenerationInput,
  type BuildPendingAssetNodeInput,
  type PendingAssetNode,
  type ContentNodeType,
  type GenerationNodeType,
  type EditKind,
  type CropRect,
  type ImageEditParams,
  type VideoClipParams,
  type EdgeInfo,
  type ProjectContext,
  type CustomActionDefinition,
  type CustomActionParameter,
  type CustomActionSecret,
  type CustomActionModel,
  type ActionProviderId,
  type ActionProviderPreset,
} from './canvas';

export {
  ExecutablePluginCardExportSchema,
  ExecutablePluginProviderExportSchema,
  ExecutablePluginModelBindingExportSchema,
  ExecutablePluginActivationReceiptSchema,
  ExecutableActionCardSchema,
  ExecutableActionPresentationSchema,
  ExecutablePluginCardDocumentSchema,
  ExecutablePluginCardRegistrationSchema,
  ExecutablePluginProviderAuthSchema,
  ExecutablePluginProviderDefinitionSchema,
  ExecutablePluginProviderDocumentSchema,
  ExecutablePluginProviderRegistrationSchema,
  ExecutablePluginModelBindingSpecSchema,
  ExecutablePluginModelBindingDocumentSchema,
  ExecutablePluginModelBindingRegistrationSchema,
  ExecutablePluginContractTestDocumentSchema,
  ExecutablePluginBindingSchema,
  ExecutablePluginAssetHandleSchema,
  ExecutablePluginAssetReadResultSchema,
  assetReachForRuntime,
  pluginRuntimeProfile,
  uploadTargetForRuntime,
  ExecutablePluginBrokerOperationSchema,
  ExecutablePluginBrokerRequestSchema,
  ExecutablePluginBrokerResponseSchema,
  ExecutablePluginInvocationSchema,
  HostedExecutablePluginCapabilitySchema,
  ExecutablePluginJsonValueSchema,
  ExecutablePluginOutputSchema,
  ExecutablePluginReferenceSchema,
  ExecutablePluginResultSchema,
  ExecutablePluginFunctionExportSchema,
  ExecutablePluginManifestSchema,
  ExecutablePluginPermissionsSchema,
  ExecutablePluginRuntimeSchema,
  ExecutablePluginModelBindingInputSchema,
  resolveModelBindingFromProvider,
  resolvePluginLanguage,
  PluginRelativePathSchema,
  diffExecutablePluginPermissions,
  composeExecutablePluginModelCards,
  executablePluginBrokerPermissionError,
  isSafePluginRelativePath,
  validateExecutablePluginPackage,
  type ExecutablePluginCardExport,
  type ExecutablePluginProviderExport,
  type ExecutablePluginModelBindingExport,
  type ExecutablePluginActivationReceipt,
  type ExecutableActionCard,
  type ExecutableActionPresentation,
  type ExecutablePluginCardDocument,
  type ExecutablePluginCardRegistration,
  type ExecutablePluginProviderAuth,
  type ExecutablePluginProviderDefinition,
  type ExecutablePluginProviderDocument,
  type ExecutablePluginProviderRegistration,
  type ExecutablePluginModelBindingSpec,
  type ExecutablePluginModelBindingDocument,
  type ExecutablePluginModelBindingRegistration,
  type ExecutablePluginContractTestDocument,
  type ExecutablePluginBinding,
  type ExecutablePluginAssetHandle,
  type ExecutablePluginAssetReadResult,
  type ExecutablePluginBrokerOperation,
  type ExecutablePluginBrokerRequest,
  type ExecutablePluginBrokerResponse,
  type ExecutablePluginInvocation,
  type HostedExecutablePluginCapability,
  type ExecutablePluginJsonValue,
  type ExecutablePluginOutput,
  type ExecutablePluginReference,
  type ExecutablePluginResult,
  type ExecutablePluginFunctionExport,
  type ExecutablePluginManifest,
  type ExecutablePluginPermissions,
  type ExecutablePluginPermissionDiff,
  type ExecutablePluginRuntime,
  type ValidatedExecutablePluginPackage,
} from './executable-plugin';

export {
  agentReadToken,
  agentReadReceiptToken,
  localConfigReadToken,
  projectReadToken,
  providerAccountReadToken,
  providerAccountsReadToken,
  providerOAuthReadToken,
  sessionReadToken,
  validateAgentReadProof,
  type AgentReadProofResult,
  type AgentReadReceiptProof,
  type AgentReadReceiptVerifier,
  type LocalConfigReadProofLike,
  type ProjectReadProofLike,
  type ProviderAccountReadProofLike,
  type ProviderOAuthReadProofLike,
  type SessionReadProofLike,
} from './agent-read-proof';

export {
  validateAgentObservation,
  type AgentObservationResult,
} from "./agent-observation";

export {
  hostMutationRejected,
  hostMutationSucceeded,
  validateHostMutationEnvelope,
  type HostMutationEnvelope,
  type HostMutationEntity,
  type HostMutationGuardResult,
  type HostMutationRecord,
} from './host-mutation-envelope';

export {
  canvasBatchDeleteReadToken,
  canvasEdgeReadToken,
  canvasEdgesReadToken,
  canvasNodeReadToken,
  canvasDownstreamTargets,
  canvasCheckpointDownstreamTargets,
  canvasPatchFields,
  isCanvasActionCheckpointLocked,
  isCanvasNodeImmutable,
  validateCanvasBatchDeleteReadProof,
  validateCanvasBatchDelete,
  validateCanvasCheckpointPatch,
  validateCanvasContentPatch,
  validateCanvasDelete,
  validateCanvasEdgeAdd,
  validateCanvasEdgeDelete,
  validateCanvasEdgePatch,
  validateCanvasEdgeReadProof,
  validateCanvasEdgesReadProof,
  validateCanvasMediaAssetPatch,
  validateCanvasNodePatch,
  validateCanvasReadProof,
  validateCanvasTimelineApply,
  validateCanvasUpdateDataFields,
  type CanvasBatchDeleteReadProofLike,
  type CanvasReadProofEdgeLike,
  type CanvasReadProofNodeLike,
  type CanvasReadProofOperation,
  type CanvasUpdateEdgeLike,
  type CanvasUpdateGuardrailResult,
  type CanvasUpdateNodeLike,
  type CanvasUpdateNodeWithIdLike,
} from './canvas-update-guardrails';

// Task types (atomic tasks + DO state)
export {
  AtomicTaskTypeSchema,
  ImageGenParamsSchema,
  VideoGenParamsSchema,
  DescriptionParamsSchema,
  UnderstandParamsSchema,
  AtomicTaskRequestSchema,
  AtomicTaskResultSchema,
  DOStepStatusSchema,
  DOStateSchema,
  type AtomicTaskType,
  type ImageGenParams,
  type VideoGenParams,
  type DescriptionParams,
  type UnderstandParams,
  type AtomicTaskRequest,
  type AtomicTaskResult,
  type DOStepStatus,
  type DOState,
} from './tasks';

// Model capability — single derivation, all consumers read fields off the
// returned profile. See model-capabilities.ts for the rationale.
export {
  capability,
  capabilityFromCustom,
  directorReferencePacket,
  directorReferencePackets,
  validateReferenceMedia,
  validateRefs,
  partitionRefs,
  referenceAssetId,
  referenceModality,
  findCompatibleModels,
  pickDefaultModel,
  type Modality,
  type RefBound,
  type ReferenceMediaConstraints,
  type ReferenceMediaMetadata,
  type Capability,
  type RefNodeLike,
  type RefPartition,
} from './model-capabilities';

// Model metadata
export {
  ModelKindSchema,
  ModelTaskSchema,
  ModelParameterTypeSchema,
  ModelParameterSchema,
  ModelProviderImplementationSchema,
  ProviderCredentialRequirementsSchema,
  ModelInputModeSchema,
  ModelInputPresentationSchema,
  ModelInputRuleSchema,
  MusicInputMappingSchema,
  ModelCardSchema,
  MODEL_CARDS,
  MOCK_MODEL_CARDS,
  normalizeModelId,
  resolveAspectRatio,
  snapAspectRatio,
  type ModelInputMode,
  type ModelInputPresentation,
  type ModelInputRule,
  type MusicInputMapping,
  type ModelKind,
  type ModelTask,
  type ModelParameterType,
  type ModelParameter,
  type ModelProviderImplementation,
  type ProviderCredentialRequirements,
  type ModelCard,
  ModelConstraintRuleSchema,
  type ModelConstraintRule,
} from './models';

export {
  GPT_IMAGE_ASPECT_RATIOS,
  GPT_IMAGE_EDGE_MULTIPLE,
  GPT_IMAGE_MAX_EDGE,
  GPT_IMAGE_MAX_PIXELS,
  GPT_IMAGE_MAX_RATIO,
  GPT_IMAGE_MIN_PIXELS,
  GPT_IMAGE_RESOLUTION_TIERS,
  GPT_IMAGE_SIZES,
  computeGptImageSize,
  formatGptImageSize,
  gptImageSizeForRatio,
  isSupportedGptImageRatio,
  parseAspectRatio,
  resolveGptImageSize,
  type GptImageResolutionTier,
  type GptImageSize,
} from './gpt-image-size';

export {
  credentialSourceKind,
  hasUnattendedCredentialSource,
  resolveCredentialSources,
  unattendedCredentialSources,
  CredentialSourceKindSchema,
  type CredentialSource,
  type CredentialSourceControl,
  type CredentialSourceKind,
} from './credential-sources';

export {
  MINIMAX_ENDPOINTS,
  minimaxBaseUrl,
  type MinimaxRegion,
} from './minimax-region';

export {
  GOOGLE_PLATFORMS,
  GooglePlatformSchema,
  googleApiBaseUrl,
  type GooglePlatform,
} from './google-platform';


export {
  CANONICAL_RESOLUTION_TIERS,
  resolutionTierPixels,
  type CanonicalResolutionTier,
} from './resolution-tiers';

export {
  applyModelParameterChange,
  coerceModelParameterInput,
  normalizeModelParametersForCard,
  validateModelCardConfiguration,
  validateParameterContractConfiguration,
  type ModelConfigurationInput,
  type ModelConfigurationValidationOptions,
  type ParameterConfigurationContract,
} from './model-constraints';

// Model routing: model-code-first upstream adapter selection.
export {
  ModelUpstreamIdSchema,
  ModelUpstreamApiShapeSchema,
  MODEL_PROVIDER_DEFINITIONS,
  MODEL_UPSTREAM_ROUTES,
  listModelUpstreamRoutes,
  resolveModelUpstreamRoute,
  missingModelRouteCredentials,
  modelRouteCredentialsSatisfied,
  ModelProviderIdSchema,
  ModelProviderApiShapeSchema,
  ProviderOAuthIdSchema,
  ProviderAccountIdSchema,
  MODEL_PROVIDER_ROUTES,
  listModelProviderRoutes,
  resolveModelProviderRoute,
  listModelCatalogEntries,
  applyModelProviderImplementation,
  listDeclaredModelUpstreamRoutes,
  buildEffectiveModelCards,
  listUserEnabledCanvasModelIds,
  listCompatibleModelCatalogEntries,
  listProviderModelSupport,
  invalidProviderModelFilters,
  unsupportedProviderModelFilterIds,
  ModelCardProviderBindingSchema,
  UserModelCardConfigSchema,
  type ModelUpstreamId,
  type ModelUpstreamApiShape,
  type ModelUpstreamRoute,
  type ModelProviderDefinition,
  type ModelProviderSupportedModel,
  type UpstreamAvailability,
  type ModelUpstreamRouteQuery,
  type ModelProviderId,
  type ModelProviderApiShape,
  type ModelProviderRoute,
  type ProviderAvailability,
  type ProviderOAuthId,
  type ProviderAccountId,
  type ProviderAccountAvailability,
  type ModelCatalogTier,
  type ModelCatalogEntry,
  type ModelCardProviderBinding,
  type UserModelCardConfig,
  type UserEnabledCanvasModelIdsQuery,
  type CompatibleModelCatalogQuery,
  type ProviderModelSupport,
  type InvalidProviderModelFilter,
  type ModelProviderRouteQuery,
} from './model-routing';

// Production action -> metadata fill -> asset -> timeline/view contracts.
export {
  AdDeliveryExportProbeSchema,
  AdDeliveryExportValidationCheckSchema,
  AdDeliveryExportValidationReceiptSchema,
  AdDeliveryMetadataSchema,
  AdDeliverySafeZoneViolationSchema,
  AdDeliverySpecProjectionSchema,
  AdDeliveryVariantSchema,
  AdEndCardSpecSchema,
  AdPackshotSpecSchema,
  AdDeliveryVisualQaReportSchema,
  AdVisualQaCheckKindSchema,
  AdVisualQaCheckSchema,
  AdVisualQaMetadataSchema,
  AnalysisBackendBenchmarkCandidateSchema,
  AnalysisBackendBenchmarkMetadataSchema,
  AnalysisBackendBenchmarkMetricSchema,
  AssetMetadataFillActionSchema,
  AudioBeatMetadataSchema,
  AudioBeatSchema,
  AudioSectionSchema,
  AudioStemAssetSchema,
  AudioStemSeparationMetadataSchema,
  AudioStemTypeSchema,
  AsrTimedSegmentSchema,
  AsrTimedTranscriptSchema,
  AsrTimedWordSchema,
  AsrTranscriptMetadataSchema,
  CaptionCueSchema,
  CharacterReferenceViewKindSchema,
  CharacterReferenceViewSchema,
  ContentCredentialActionSchema,
  ContentCredentialAssertionSchema,
  ContentCredentialIngredientRelationshipSchema,
  ContentCredentialIngredientSchema,
  ContentCredentialModeSchema,
  ContentCredentialSignatureStatusSchema,
  ContentCredentialsMetadataSchema,
  ImageComfyuiApiFormatSchema,
  ImageComfyuiCustomNodeSchema,
  ImageComfyuiExecutionSchema,
  ImageComfyuiInputKindSchema,
  ImageComfyuiInputSlotSchema,
  ImageComfyuiModelReferenceSchema,
  ImageComfyuiModelTypeSchema,
  ImageComfyuiOutputMediaTypeSchema,
  ImageComfyuiOutputSchema,
  ImageComfyuiOutputStatusSchema,
  ImageComfyuiRunnerMetadataSchema,
  ImageEmbeddingBaselineForSchema,
  ImageEmbeddingDistanceMetricSchema,
  ImageEmbeddingStoreItemSchema,
  ImageEmbeddingStoreMetadataSchema,
  ImageStoryboardMetadataSchema,
  LyricsAlignmentMetadataSchema,
  LyricsAlignmentUnitSchema,
  LyricsUnmatchedRangeSchema,
  ProductionMetadataSchema,
  ProductLogoQaCheckKindSchema,
  ProductLogoQaCheckSchema,
  ProductLogoQaMetadataSchema,
  ProductLogoQaReferenceSchema,
  ReferenceDownloadFileSchema,
  ReferenceDownloadMetadataSchema,
  ReferenceDownloadSourceLedgerSchema,
  ReferenceShotSchema,
  ReferenceVideoMetadataSchema,
  RightsMetadataSchema,
  SemanticReferenceDownstreamUsageSchema,
  SemanticReferenceRoleKindSchema,
  SemanticReferenceRoleSchema,
  SemanticReferenceRolesMetadataSchema,
  StoryboardPromptPackSchema,
  StoryboardPromptSchema,
  TalkingHeadMetadataSchema,
  TextCutSchema,
  TranscriptWordSchema,
  VideoVisualMomentMetadataSchema,
  VisualMomentCandidateSchema,
  applyAssetMetadataFill,
  assertReferenceCanBeRemixed,
  buildAdDeliveryExportValidationReceipt,
  buildAnalysisBackendBenchmarkVerdict,
  buildBeatEditHints,
  buildBeatSectionCutPlan,
  buildAdDeliveryChecklist,
  buildCaptionItemFromTalkingHeadMetadata,
  buildCaptionItemFromLyricsAlignmentMetadata,
  buildProductLogoQaVerdict,
  buildReferenceRightsLedger,
  buildStoryboardPromptPackFromMetadata,
  buildVisualMomentClipLibrary,
  projectAsrTimedTranscriptWords,
  type AdDeliveryExportProbe,
  type AdDeliveryExportValidationReceipt,
  type AdDeliveryMetadata,
  type AdDeliverySpecProjection,
  type AdDeliveryVisualQaReport,
  type AdVisualQaCheck,
  type AdVisualQaCheckKind,
  type AdVisualQaMetadata,
  type AnalysisBackendBenchmarkCandidate,
  type AnalysisBackendBenchmarkMetadata,
  type AnalysisBackendBenchmarkMetric,
  type AssetMetadataFillAction,
  type AudioBeatMetadata,
  type AudioStemAsset,
  type AudioStemSeparationMetadata,
  type AudioStemType,
  type AsrTimedSegment,
  type AsrTimedTranscript,
  type AsrTimedWord,
  type AsrTranscriptMetadata,
  type CharacterReferenceView,
  type CharacterReferenceViewKind,
  type ContentCredentialAction,
  type ContentCredentialAssertion,
  type ContentCredentialIngredient,
  type ContentCredentialIngredientRelationship,
  type ContentCredentialMode,
  type ContentCredentialSignatureStatus,
  type ContentCredentialsMetadata,
  type ImageComfyuiApiFormat,
  type ImageComfyuiCustomNode,
  type ImageComfyuiInputKind,
  type ImageComfyuiInputSlot,
  type ImageComfyuiModelReference,
  type ImageComfyuiModelType,
  type ImageComfyuiOutput,
  type ImageComfyuiRunnerMetadata,
  type ImageEmbeddingBaselineFor,
  type ImageEmbeddingDistanceMetric,
  type ImageEmbeddingStoreItem,
  type ImageEmbeddingStoreMetadata,
  type ImageStoryboardMetadata,
  type LyricsAlignmentMetadata,
  type ProductionAsset,
  type ProductionMetadata,
  type ProductLogoQaCheck,
  type ProductLogoQaMetadata,
  type ProductLogoQaReference,
  type ReferenceDownloadFile,
  type ReferenceDownloadMetadata,
  type ReferenceDownloadSourceLedger,
  type ReferenceVideoMetadata,
  type SemanticReferenceRole,
  type SemanticReferenceRolesMetadata,
  type StoryboardPromptPack,
  type TalkingHeadMetadata,
  type VideoVisualMomentMetadata,
} from './production-metadata';

// Declared asset metadata kinds: the open registry behind the published
// asset-metadata-fill-action contract.
export {
  MediaTranscriptMetadataSchema,  getDeclaredAssetMetadataKind,
  listDeclaredAssetMetadataKinds,
  parseAssetMetadataFillAction,
  parseDeclaredAssetMetadata,
  registerAssetMetadataKind,
  summarizeTranscript,
  transcriptContentHashInput,
  type DeclaredAssetMetadataKind,
  type MediaDescriptionMetadata,
  type MediaTranscriptMetadata,
  type ParsedAssetMetadataFillAction,
} from './asset-metadata-registry';

// Local speech catalog selectors: one source for GUI and CLI alike.
export {
  asrModelValue,
  isLocalAsrModelEntry,
  isLocalSpeechModelEntry,
  isLocalTtsModelEntry,
  listLocalSpeechModelCards,
  localSpeechCapability,
  localSpeechModelCard,
  localSpeechModelValue,
  resolveLocalSpeechModelId,
  ttsModelValue,
  type LocalSpeechCapability,
  type LocalSpeechCatalogEntry,
  type LocalSpeechModelCard,
} from './local-speech-catalog';

// Canvas operations class
export { Canvas } from './canvas-ops';
export type {
  ExecuteGenerationResult,
} from './canvas-ops';

// Re-export types from Canvas for convenience
export type {
  BroadcastFn,
  NodeInfo,
  CreateNodeResult,
  CreateLinkedNodeResult,
  TaskStatusResult,
} from './canvas-ops';

// Loro sync client
export {
  computeActionBuildPlan,
  computeCanvasActionBuildPlan,
  summarizeActionBuildInvocations,
  type ActionBuildGraphEdge,
  type ActionBuildGraphNode,
  type ActionBuildGraphReader,
  type ActionBuildInvocationEstimate,
  type ActionBuildInvocationKind,
  type ActionBuildModality,
  type ActionBuildPlan,
  type ActionBuildPlanEntry,
  type CanvasActionBuildGraph,
} from "./action-build-plan";

export {
  DEFAULT_CANVAS_ID,
  createProjectCanvas,
  createProjectTimeline,
  copyTimelineActionToCanvas,
  deleteProjectCanvas,
  deleteProjectTimeline,
  detachTimelineFromCanvas,
  ensureProjectCanvas,
  listProjectCanvases,
  listProjectTimelines,
  listStandaloneTimelines,
  projectCanvasReadToken,
  projectTimelineReadToken,
  projectTimelineRevisionId,
  readProjectTimeline,
  reconcileProjectTimelineOwnership,
  renameProjectCanvas,
  resolveTimelineRenderTarget,
  attachTimelineToCanvas,
  updateProjectTimelineState,
  type ProjectCanvas,
  type ProjectCanvasDeleteResult,
  type ProjectCanvasMutationResult,
  type ProjectTimeline,
  type ProjectTimelineDeleteResult,
  type ProjectTimelineMutationResult,
  type TimelineOwner,
  type TimelineOwnershipReconciliation,
  type TimelineRenderTarget,
} from "./project-workspace";
export {
  PROJECT_ASSET_RENDER_CANVAS_ID,
  requestTimelineRender,
  type TimelineRenderRequestInput,
  type TimelineRenderRequestResult,
} from "./timeline-render";

export {
  EDGE_IDENTITY_CONTAINER,
  NODE_UPSTREAMS_CONTAINER,
  canvasGraphReconciliationChanged,
  clearNodeUpstreamRefs,
  deleteNodeUpstreamRef,
  ensureCanvasGraphIdentity,
  listNodeOwnedEdges,
  readNodeUpstreamRefs,
  reconcileCanvasGraph,
  upsertNodeUpstreamRef,
  type CanvasGraphReconciliation,
  type NodeOwnedEdge,
} from "./node-upstreams";

// Loro sync client
export { LoroSyncClient, loroSyncUpdateId } from './loro-client';
export type { LoroSyncClientOptions } from './loro-client';

// Prompt parsing (mixed-modality @-mentions)
export {
  parsePromptParts,
  extractPromptText,
  normalizePromptInput,
  composePromptWithTextRefs,
  extractAssetRefs,
  buildMention,
  hasAssetMentions,
  appendUnmentionedGlobalReferences,
  composeOrderedPromptContent,
  renderPositionalReferencePrompt,
  type PromptPart,
  type OrderedPromptContentPart,
  type PositionalReferencePromptInput,
  type AssetRef,
} from './prompt';

// Collaboration visibility (presence + activity)
export * from './presence';

// Timeline YAML projection (agent-facing surface)
export {
  timelineDslToYaml,
  timelineDslFromYaml,
  timelineDslCanonicalJson,
  timelineDslHash,
  resolveFromExpression,
} from './timeline-yaml';
export type {
  ResolvedTimelineDsl,
  ResolvedItem,
  ResolvedTrack,
  FromYamlResult,
} from './timeline-yaml';
export {
  parseFromExpression,
  type FromExpression,
} from './timeline-from-expression';
export {
  DEFAULT_TIMELINE_KEYFRAME_INTERPOLATION,
  sampleTimelineKeyframeChannel,
  TIMELINE_KEYFRAME_CHANNEL_ANNOTATIONS,
  TIMELINE_KEYFRAME_CHANNELS,
  TIMELINE_KEYFRAME_INTERPOLATIONS,
  TIMELINE_KEYFRAME_SAMPLING_POLICY,
  TimelineItemKeyframesSchema,
  TimelineScalarKeyframeSchema,
  TimelineVectorKeyframeSchema,
  timelineKeyframeFrameIssues,
  validateTimelineItemKeyframes,
  type TimelineItemKeyframes,
  type TimelineKeyframeChannel,
  type TimelineKeyframeInterpolation,
  type TimelineKeyframeSampleEntry,
  type TimelineScalarKeyframe,
  type TimelineVectorKeyframe,
} from './timeline-keyframes';
export {
  canMergeTimelineItemsAcrossMaskBoundary,
  createDefaultTimelineItemMask,
  DEFAULT_TIMELINE_ITEM_MASK,
  TIMELINE_MASK_ANIMATION_BINDINGS,
  TIMELINE_MASK_APPLIES_TO_ITEM_TYPES,
  TIMELINE_MASK_CAPABILITY_ANNOTATION,
  TIMELINE_MASK_EXCLUDED_ITEM_TYPES,
  TIMELINE_MASK_FEATHER_BLUR_DIVISOR,
  TIMELINE_MASK_FIELD_ANNOTATIONS,
  TIMELINE_MASK_FIELDS,
  TIMELINE_MASK_KEYFRAME_CHANNELS,
  TIMELINE_MASK_SCALAR_ANIMATION_BINDINGS,
  TIMELINE_MASK_SHAPE_ANNOTATIONS,
  TIMELINE_MASK_SHAPES,
  TIMELINE_MASK_STATIC_CONTROL_BINDINGS,
  TIMELINE_MASK_VECTOR_ANIMATION_BINDINGS,
  TimelineItemMaskSchema,
  validateTimelineItemMask,
  type TimelineItemMask,
  type TimelineMaskAnimationBinding,
  type TimelineMaskAnimatedField,
  type TimelineMaskAnimatedValueKind,
  type TimelineMaskField,
  type TimelineMaskKeyframeSample,
  type TimelineMaskKeyframeChannel,
  type TimelineMaskNumberInputAnnotation,
  type TimelineMaskRenderPrimitive,
  type TimelineMaskScalarAnimatedField,
  type TimelineMaskScalarAnimationBinding,
  type TimelineMaskShape,
  type TimelineMaskStaticControlAnnotation,
  type TimelineMaskStaticControlBinding,
  type TimelineMaskVectorAnimatedField,
  type TimelineMaskVectorAnimationBinding,
} from './timeline-mask';
export {
  TIMELINE_DSL_DEFINITION,
  TIMELINE_DSL_ITEM_TYPES,
  TIMELINE_DSL_TRACK_CATEGORIES,
  TIMELINE_MASK_KEYFRAMES_DSL_EXAMPLE,
  TimelineDslItemSchema,
  TimelineDslSchema,
  TimelineDslTrackSchema,
  TIMELINE_DSL_SEMANTIC_RULES,
  timelineMaskKeyframeSemanticIssues,
  validateTimelineDsl,
  type TimelineDslDefinition,
  type TimelineDslValidationIssue,
  type TimelineDslValidationResult,
  type TimelineMaskKeyframeSemanticIssue,
} from './timeline-dsl-schema';
export {
  renderTimelineAgentWorkflowReference,
  renderTimelineDslMarkdown,
  renderTimelineMaskSkillReference,
  renderTimelineMaskKeyframesExampleYaml,
} from './timeline-dsl-docs';

// Asset metadata (D1 assets + asset_refs tables)
export * from './asset-scope-cascade';

export {
  AssetKindSchema,
  AssetMetadataSchema,
  AssetSourceSchema,
  AssetSchema,
  AssetRefRowSchema,
  assetReadToken,
  assetRefReadToken,
  type AssetKind,
  type AssetMetadata,
  type AssetSource,
  type Asset,
  type AssetRefRow,
  type AssetReadProofLike,
  type AssetRefReadProofLike,
} from './assets';

export {
  createMediaAssetCowNodeData,
  isMediaNodeType,
} from './media-asset-replacement';

// Serializable Action Specs and asset-edit invocations.
export {
  ActionFamilySchema,
  ActionExecutorSchema,
  ActionOperationSpecSchema,
  ActionSpecSchema,
  ActionInvocationModeSchema,
  ActionSurfaceSchema,
  invocationModeForSurface,
  type ActionFamily,
  type ActionExecutor,
  type ActionOperationSpec,
  type ActionSpec,
  type ActionInvocationMode,
  type ActionSurface,
} from './actions/spec';
export {
  ASSET_ACTION_ID,
  BUILT_IN_ASSET_ACTION_SPECS,
  AssetEditActionInvocationSchema,
  createAssetActionInvocation,
  resolveAssetActionOutputKind,
  legacyEditOriginForSurface,
  actionSourceModel,
  type AssetActionId,
  type AssetEditActionInvocation,
  type CreateAssetActionInvocationInput,
} from './actions/asset-edit';

export {
  TextAppliedRevisionSchema,
  TextRevisionActorSchema,
  TextRevisionContentDescriptorSchema,
  TextRevisionHistoryEntrySchema,
  type TextAppliedRevision,
  type TextRevisionActor,
  type TextRevisionContentDescriptor,
  type TextRevisionHistoryEntry,
} from './text-revisions';

// Pipeline types
export {
  AssetStatusSchema,
  TaskStateSchema,
  PipelineTaskDefSchema,
  SuperstepDefSchema,
  PipelineDefSchema,
  TaskRuntimeStateSchema,
  PipelineRuntimeStateSchema,
  type AssetStatus as AssetStatusType,
  type TaskState,
  type PipelineTaskDef,
  type SuperstepDef,
  type PipelineDef,
  type TaskRuntimeState,
  type PipelineRuntimeState,
} from './pipeline';

export {
  ProviderUsageAuditEventSchema,
  ProviderUsagePricingSourceSchema,
  ProviderUsageStatusSchema,
  type ProviderUsageAuditEvent,
  type ProviderUsagePricingSource,
  type ProviderUsageStatus,
} from './provider-usage';
