/**
 * @file index.ts
 * @description Main entry point for shared type definitions used across Frontend and Backend.
 * @module packages.shared-types.src
 *
 * @responsibility
 * - Exports all Zod schemas and TypeScript types used across the monorepo
 * - Acts as the Single Source of Truth for API contracts and Data Models
 * - Categorizes types into Canvas, Task, Model, and Pipeline domains
 *
 * @exports
 * - *Schema: Zod schemas for runtime validation
 * - type *: TypeScript type definitions inferred from Zod
 */

// Canvas types + constants (single source of truth)
export {
  // Schemas
  PositionSchema,
  NodeStatusSchema,
  NodeDataSchema,
  CanvasNodeSchema,
  CanvasEdgeSchema,
  LoroDocumentStateSchema,
  NodeInfoSchema,
  EdgeInfoSchema,
  ProjectContextSchema,
  // ReactFlow types
  RF_NODE_TYPE,
  ACTION_TYPE,
  EDIT_KIND,
  AGENT_NODE_TYPE_MAP,
  // Edit-node param schemas
  CropRectSchema,
  ImageEditParamsSchema,
  VideoClipParamsSchema,
  // Agent-facing types
  NodeType,
  ALL_NODE_TYPES,
  CONTENT_NODE_TYPES,
  GENERATION_NODE_TYPES,
  isGenerationNodeType,
  FrontendNodeType,
  ProposalType,
  TaskStatus,
  AssetStatus,
  // Custom actions
  ACTION_PROVIDER_PRESETS,
  ACTION_PROVIDER_IDS,
  ActionProviderIdSchema,
  ActionProviderRefSchema,
  CustomActionModelSchema,
  CustomActionParameterSchema,
  CustomActionSecretSchema,
  CustomActionDefinitionSchema,
  normalizeActionProviderId,
  mergeActionProviderSecrets,
  isCustomActionType,
  getCustomActionId,
  // Validation & Builders
  validateGenerationInput,
  buildPendingAssetNode,
  buildGenerationPayload,
  extractLabelFromPrompt,
  type GenerationConfig,
  // TypeScript types
  type Position,
  type NodeStatus,
  type NodeData,
  type CanvasNode,
  type CanvasEdge,
  type LoroDocumentState,
  type ValidateGenerationInput,
  type BuildPendingAssetNodeInput,
  type PendingAssetNode,
  type ContentNodeType,
  type GenerationNodeType,
  type EditKind,
  type CropRect,
  type ImageEditParams,
  type VideoClipParams,
  type EdgeInfo,
  type ProjectContext,
  type CustomActionDefinition,
  type CustomActionParameter,
  type CustomActionSecret,
  type CustomActionModel,
  type ActionProviderId,
  type ActionProviderPreset,
} from './canvas';

export {
  agentReadToken,
  agentReadReceiptToken,
  localConfigReadToken,
  projectReadToken,
  providerAccountReadToken,
  providerAccountsReadToken,
  providerOAuthReadToken,
  sessionReadToken,
  validateAgentReadProof,
  type AgentReadProofResult,
  type AgentReadReceiptProof,
  type AgentReadReceiptVerifier,
  type LocalConfigReadProofLike,
  type ProjectReadProofLike,
  type ProviderAccountReadProofLike,
  type ProviderOAuthReadProofLike,
  type SessionReadProofLike,
} from './agent-read-proof';

export {
  hostMutationRejected,
  hostMutationSucceeded,
  validateHostMutationEnvelope,
  type HostMutationEnvelope,
  type HostMutationEntity,
  type HostMutationGuardResult,
  type HostMutationRecord,
} from './host-mutation-envelope';

export {
  canvasBatchDeleteReadToken,
  canvasEdgeReadToken,
  canvasEdgesReadToken,
  canvasNodeReadToken,
  canvasDownstreamTargets,
  canvasCheckpointDownstreamTargets,
  canvasPatchFields,
  isCanvasActionCheckpointLocked,
  validateCanvasBatchDeleteReadProof,
  validateCanvasBatchDelete,
  validateCanvasCheckpointPatch,
  validateCanvasContentPatch,
  validateCanvasDelete,
  validateCanvasEdgeAdd,
  validateCanvasEdgeDelete,
  validateCanvasEdgePatch,
  validateCanvasEdgeReadProof,
  validateCanvasEdgesReadProof,
  validateCanvasMediaAssetPatch,
  validateCanvasNodePatch,
  validateCanvasReadProof,
  validateCanvasTimelineApply,
  validateCanvasUpdateDataFields,
  type CanvasBatchDeleteReadProofLike,
  type CanvasReadProofEdgeLike,
  type CanvasReadProofNodeLike,
  type CanvasReadProofOperation,
  type CanvasUpdateEdgeLike,
  type CanvasUpdateGuardrailResult,
  type CanvasUpdateNodeLike,
  type CanvasUpdateNodeWithIdLike,
} from './canvas-update-guardrails';

// Task types (atomic tasks + DO state)
export {
  AtomicTaskTypeSchema,
  ImageGenParamsSchema,
  VideoGenParamsSchema,
  DescriptionParamsSchema,
  UnderstandParamsSchema,
  AtomicTaskRequestSchema,
  AtomicTaskResultSchema,
  DOStepStatusSchema,
  DOStateSchema,
  type AtomicTaskType,
  type ImageGenParams,
  type VideoGenParams,
  type DescriptionParams,
  type UnderstandParams,
  type AtomicTaskRequest,
  type AtomicTaskResult,
  type DOStepStatus,
  type DOState,
} from './tasks';

// Model capability — single derivation, all consumers read fields off the
// returned profile. See model-capabilities.ts for the rationale.
export {
  capability,
  validateRefs,
  partitionRefs,
  pickDefaultModel,
  type Modality,
  type RefBound,
  type Capability,
  type RefNodeLike,
  type RefPartition,
} from './model-capabilities';

// Model metadata
export {
  ModelKindSchema,
  ModelParameterTypeSchema,
  ModelParameterSchema,
  ModelInputModeSchema,
  ModelInputRuleSchema,
  ModelCardSchema,
  MODEL_CARDS,
  MOCK_MODEL_CARDS,
  normalizeModelId,
  resolveAspectRatio,
  snapAspectRatio,
  type ModelInputMode,
  type ModelInputRule,
  type ModelKind,
  type ModelParameterType,
  type ModelParameter,
  type ModelCard,
} from './models';

// Model routing: model-code-first upstream adapter selection.
export {
  ModelUpstreamIdSchema,
  ModelUpstreamApiShapeSchema,
  MODEL_PROVIDER_DEFINITIONS,
  MODEL_UPSTREAM_ROUTES,
  listModelUpstreamRoutes,
  resolveModelUpstreamRoute,
  ModelProviderIdSchema,
  ModelProviderApiShapeSchema,
  ProviderOAuthIdSchema,
  ProviderAccountIdSchema,
  MODEL_PROVIDER_ROUTES,
  listModelProviderRoutes,
  resolveModelProviderRoute,
  listModelCatalogEntries,
  listProviderModelSupport,
  invalidProviderModelFilters,
  unsupportedProviderModelFilterIds,
  type ModelUpstreamId,
  type ModelUpstreamApiShape,
  type ModelUpstreamRoute,
  type ModelProviderDefinition,
  type ModelProviderSupportedModel,
  type UpstreamAvailability,
  type ModelUpstreamRouteQuery,
  type ModelProviderId,
  type ModelProviderApiShape,
  type ModelProviderRoute,
  type ProviderAvailability,
  type ProviderOAuthId,
  type ProviderAccountId,
  type ProviderAccountAvailability,
  type ModelCatalogTier,
  type ModelCatalogEntry,
  type ProviderModelSupport,
  type InvalidProviderModelFilter,
  type ModelProviderRouteQuery,
} from './model-routing';

// Agent-readable motion graphics composition contract.
export {
  MgAnimationSchema,
  MgCompositionLayerSchema,
  MgCompositionSpecSchema,
  MgShapeLayerSchema,
  MgTextLayerSchema,
  buildMgOverlayManifest,
  evaluateMgLayerAtFrame,
  renderMgCompositionHtml,
  type MgAnimation,
  type MgCompositionLayer,
  type MgCompositionSpec,
  type MgEvaluatedLayerStyle,
  type MgOverlayManifest,
} from './mg-composition';

// Production action -> metadata fill -> asset -> timeline/view contracts.
export {
  AdDeliveryExportProbeSchema,
  AdDeliveryExportValidationCheckSchema,
  AdDeliveryExportValidationReceiptSchema,
  AdDeliveryMetadataSchema,
  AdDeliverySafeZoneViolationSchema,
  AdDeliverySpecProjectionSchema,
  AdDeliveryVariantSchema,
  AdEndCardSpecSchema,
  AdPackshotSpecSchema,
  AdDeliveryVisualQaReportSchema,
  AdVisualQaCheckKindSchema,
  AdVisualQaCheckSchema,
  AdVisualQaMetadataSchema,
  AnalysisBackendBenchmarkCandidateSchema,
  AnalysisBackendBenchmarkMetadataSchema,
  AnalysisBackendBenchmarkMetricSchema,
  AssetMetadataFillActionSchema,
  AudioBeatMetadataSchema,
  AudioBeatSchema,
  AudioSectionSchema,
  AudioStemAssetSchema,
  AudioStemSeparationMetadataSchema,
  AudioStemTypeSchema,
  AsrTranscriptMetadataSchema,
  CaptionCueSchema,
  CharacterReferenceViewKindSchema,
  CharacterReferenceViewSchema,
  ContentCredentialActionSchema,
  ContentCredentialAssertionSchema,
  ContentCredentialIngredientRelationshipSchema,
  ContentCredentialIngredientSchema,
  ContentCredentialModeSchema,
  ContentCredentialSignatureStatusSchema,
  ContentCredentialsMetadataSchema,
  ImageComfyuiApiFormatSchema,
  ImageComfyuiCustomNodeSchema,
  ImageComfyuiExecutionSchema,
  ImageComfyuiInputKindSchema,
  ImageComfyuiInputSlotSchema,
  ImageComfyuiModelReferenceSchema,
  ImageComfyuiModelTypeSchema,
  ImageComfyuiOutputMediaTypeSchema,
  ImageComfyuiOutputSchema,
  ImageComfyuiOutputStatusSchema,
  ImageComfyuiRunnerMetadataSchema,
  ImageEmbeddingBaselineForSchema,
  ImageEmbeddingDistanceMetricSchema,
  ImageEmbeddingStoreItemSchema,
  ImageEmbeddingStoreMetadataSchema,
  ImageStoryboardMetadataSchema,
  LyricsAlignmentMetadataSchema,
  LyricsAlignmentUnitSchema,
  LyricsUnmatchedRangeSchema,
  ProductionMetadataSchema,
  ProductLogoQaCheckKindSchema,
  ProductLogoQaCheckSchema,
  ProductLogoQaMetadataSchema,
  ProductLogoQaReferenceSchema,
  ReferenceDownloadFileSchema,
  ReferenceDownloadMetadataSchema,
  ReferenceDownloadSourceLedgerSchema,
  ReferenceShotSchema,
  ReferenceVideoMetadataSchema,
  RightsMetadataSchema,
  SemanticReferenceDownstreamUsageSchema,
  SemanticReferenceRoleKindSchema,
  SemanticReferenceRoleSchema,
  SemanticReferenceRolesMetadataSchema,
  StoryboardPromptPackSchema,
  StoryboardPromptSchema,
  TalkingHeadMetadataSchema,
  TextCutSchema,
  TranscriptWordSchema,
  VideoVisualMomentMetadataSchema,
  VisualMomentCandidateSchema,
  applyAssetMetadataFill,
  assertReferenceCanBeRemixed,
  buildAdDeliveryExportValidationReceipt,
  buildAnalysisBackendBenchmarkVerdict,
  buildBeatEditHints,
  buildBeatSectionCutPlan,
  buildAdDeliveryChecklist,
  buildCaptionItemFromTalkingHeadMetadata,
  buildCaptionItemFromLyricsAlignmentMetadata,
  buildProductLogoQaVerdict,
  buildReferenceRightsLedger,
  buildStoryboardPromptPackFromMetadata,
  buildVisualMomentClipLibrary,
  type AdDeliveryExportProbe,
  type AdDeliveryExportValidationReceipt,
  type AdDeliveryMetadata,
  type AdDeliverySpecProjection,
  type AdDeliveryVisualQaReport,
  type AdVisualQaCheck,
  type AdVisualQaCheckKind,
  type AdVisualQaMetadata,
  type AnalysisBackendBenchmarkCandidate,
  type AnalysisBackendBenchmarkMetadata,
  type AnalysisBackendBenchmarkMetric,
  type AssetMetadataFillAction,
  type AudioBeatMetadata,
  type AudioStemAsset,
  type AudioStemSeparationMetadata,
  type AudioStemType,
  type AsrTranscriptMetadata,
  type CharacterReferenceView,
  type CharacterReferenceViewKind,
  type ContentCredentialAction,
  type ContentCredentialAssertion,
  type ContentCredentialIngredient,
  type ContentCredentialIngredientRelationship,
  type ContentCredentialMode,
  type ContentCredentialSignatureStatus,
  type ContentCredentialsMetadata,
  type ImageComfyuiApiFormat,
  type ImageComfyuiCustomNode,
  type ImageComfyuiInputKind,
  type ImageComfyuiInputSlot,
  type ImageComfyuiModelReference,
  type ImageComfyuiModelType,
  type ImageComfyuiOutput,
  type ImageComfyuiRunnerMetadata,
  type ImageEmbeddingBaselineFor,
  type ImageEmbeddingDistanceMetric,
  type ImageEmbeddingStoreItem,
  type ImageEmbeddingStoreMetadata,
  type ImageStoryboardMetadata,
  type LyricsAlignmentMetadata,
  type ProductionAsset,
  type ProductionMetadata,
  type ProductLogoQaCheck,
  type ProductLogoQaMetadata,
  type ProductLogoQaReference,
  type ReferenceDownloadFile,
  type ReferenceDownloadMetadata,
  type ReferenceDownloadSourceLedger,
  type ReferenceVideoMetadata,
  type SemanticReferenceRole,
  type SemanticReferenceRolesMetadata,
  type StoryboardPromptPack,
  type TalkingHeadMetadata,
  type VideoVisualMomentMetadata,
} from './production-metadata';

// Canvas operations class
export { Canvas } from './canvas-ops';
export type {
  ExecuteGenerationResult,
} from './canvas-ops';

// Re-export types from Canvas for convenience
export type {
  BroadcastFn,
  NodeInfo,
  CreateNodeResult,
  CreateLinkedNodeResult,
  TaskStatusResult,
} from './canvas-ops';

// Loro sync client
export { LoroSyncClient } from './loro-client';
export type { LoroSyncClientOptions } from './loro-client';

// Prompt parsing (mixed-modality @-mentions)
export {
  parsePromptParts,
  extractPromptText,
  normalizePromptInput,
  composePromptWithTextRefs,
  extractAssetRefs,
  buildMention,
  hasAssetMentions,
  type PromptPart,
  type AssetRef,
} from './prompt';

// Collaboration visibility (presence + activity)
export * from './presence';

// Timeline YAML projection (agent-facing surface)
export {
  timelineDslToYaml,
  timelineDslFromYaml,
  timelineDslHash,
  parseFromExpression,
  resolveFromExpression,
} from './timeline-yaml';
export type {
  ResolvedTimelineDsl,
  ResolvedItem,
  ResolvedTrack,
  FromExpression,
  FromYamlResult,
} from './timeline-yaml';

// Asset metadata (D1 assets + asset_refs tables)
export {
  AssetKindSchema,
  AssetMetadataSchema,
  AssetSourceSchema,
  AssetSchema,
  AssetRefRowSchema,
  assetReadToken,
  assetRefReadToken,
  type AssetKind,
  type AssetMetadata,
  type AssetSource,
  type Asset,
  type AssetRefRow,
  type AssetReadProofLike,
  type AssetRefReadProofLike,
} from './assets';

export {
  createMediaAssetCowNodeData,
  isMediaNodeType,
} from './media-asset-replacement';

export {
  TextAppliedRevisionSchema,
  TextRevisionActorSchema,
  TextRevisionContentDescriptorSchema,
  TextRevisionHistoryEntrySchema,
  type TextAppliedRevision,
  type TextRevisionActor,
  type TextRevisionContentDescriptor,
  type TextRevisionHistoryEntry,
} from './text-revisions';

export {
  TimelineAppliedRevisionSchema,
  TimelineRevisionActorSchema,
  TimelineRevisionContentDescriptorSchema,
  TimelineRevisionDependenciesSchema,
  TimelineRevisionHistoryEntrySchema,
  type TimelineAppliedRevision,
  type TimelineRevisionActor,
  type TimelineRevisionContentDescriptor,
  type TimelineRevisionDependencies,
  type TimelineRevisionHistoryEntry,
} from './timeline-revisions';

// Pipeline types
export {
  AssetStatusSchema,
  TaskStateSchema,
  PipelineTaskDefSchema,
  SuperstepDefSchema,
  PipelineDefSchema,
  TaskRuntimeStateSchema,
  PipelineRuntimeStateSchema,
  type AssetStatus as AssetStatusType,
  type TaskState,
  type PipelineTaskDef,
  type SuperstepDef,
  type PipelineDef,
  type TaskRuntimeState,
  type PipelineRuntimeState,
} from './pipeline';
