packages:
  - 'apps/api-cf'
  - 'apps/render-server'
  - 'apps/web'
  - 'apps/web-tanstack'
  - 'packages/remotion-*'
  - 'packages/shared-*'
  - 'packages/action-sdk'
  - 'packages/web-ui'
  - 'packages/cli'
  - 'packages/claude-code-plugin'
