packages:
  - 'apps/api-cf'
  - 'apps/desktop'
  - 'apps/local-api'
  - 'apps/render-server'
  - 'apps/web'
  - 'packages/remotion-*'
  - 'packages/shared-*'
  - 'packages/action-sdk'
  - 'packages/clash-sdk/js'
  - 'packages/web-ui'
  - 'packages/cli'
  - 'packages/clash-bridge'
  - 'packages/claude-code-plugin'
