packages:
  - 'apps/api-cf'
  - 'apps/desktop'
  - 'apps/docs'
  - 'apps/local-api'
  - 'apps/render-server'
  - 'apps/web'
  - 'packages/remotion-*'
  - 'packages/director-*'
  - 'packages/shared-*'
  - 'packages/action-sdk'
  - 'packages/asset-sdk'
  - 'packages/clash-sdk/js'
  - 'packages/gui'
  - 'packages/web-ui'
  - 'packages/cli'
  - 'packages/mcp-server'
  - 'plugins/*'
supportedArchitectures:
  cpu: [arm64, x64]
allowBuilds:
  '@swc/core': set this to true or false
  core-js-pure: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  ffmpeg-static: true
  sharp: set this to true or false
  workerd: set this to true or false
patchedDependencies:
  '@openma/common@0.5.0': 'patches/@openma__common@0.5.0.patch'
