// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/landing": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/marketplace": {
    params: {};
  };
  "/editor-standalone": {
    params: {};
  };
  "/auth/cli": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/landing" | "/login" | "/projects" | "/projects/:id" | "/settings" | "/billing" | "/marketplace" | "/editor-standalone" | "/auth/cli" | "/terms" | "/privacy";
  };
  "layouts/AppLayout.tsx": {
    id: "layouts/AppLayout";
    page: "/" | "/landing" | "/login" | "/projects" | "/projects/:id" | "/settings" | "/billing" | "/marketplace" | "/editor-standalone" | "/auth/cli" | "/terms" | "/privacy";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/landing";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/project.$id.tsx": {
    id: "routes/project.$id";
    page: "/projects/:id";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/billing.tsx": {
    id: "routes/billing";
    page: "/billing";
  };
  "routes/marketplace.tsx": {
    id: "routes/marketplace";
    page: "/marketplace";
  };
  "routes/editor-standalone.tsx": {
    id: "routes/editor-standalone";
    page: "/editor-standalone";
  };
  "routes/auth.cli.tsx": {
    id: "routes/auth.cli";
    page: "/auth/cli";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/AppLayout": typeof import("./app/layouts/AppLayout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/landing": typeof import("./app/routes/landing.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/projects": typeof import("./app/routes/projects.tsx");
  "routes/project.$id": typeof import("./app/routes/project.$id.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/billing": typeof import("./app/routes/billing.tsx");
  "routes/marketplace": typeof import("./app/routes/marketplace.tsx");
  "routes/editor-standalone": typeof import("./app/routes/editor-standalone.tsx");
  "routes/auth.cli": typeof import("./app/routes/auth.cli.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
};