import type {
  PluginAuthDeclaration,
  PluginAuthFormItem,
} from "@clash/shared-types";
import { googleBaseUrl } from "./base-url.js";
import { googleModelPath } from "./model-path.js";
import {
  valueOutput,
  type ExecutorContext,
  type ExecutorStep,
  type ProviderExecutor,
} from "./executor-contract";
import type { ExecutablePluginInvocation } from "@clash/shared-types/executable-plugin";
import { aspectRatioLabel } from "@clash/shared-types/executable-plugin";

/**
 * Google's generateContent surface, for both hosts.
 *
 * Verified against Google with a real key: `generativelanguage.googleapis.com/v1beta` and
 * `aiplatform.googleapis.com/v1` both answer `:generateContent` authenticated by `x-goog-api-key`,
 * and neither needs a project, a location, a service account or a signed JWT. The paths differ —
 * `/models/{model}` against one, `/publishers/google/models/{model}` against the other — and that
 * is the whole of the difference.
 *
 * Synchronous, so `submit` returns the finished arm and `poll` never runs. The contract allows that
 * and it is worth stating: an executor is not required to be asynchronous, only to be honest about
 * which it is.
 */

interface FetchLike {
  (
    url: string,
    init?: {
      method?: string;
      headers?: Record<string, string>;
      body?: string;
    },
  ): Promise<{
    ok: boolean;
    status: number;
    statusText: string;
    text(): Promise<string>;
  }>;
}

type GoogleCredentials = {
  accessToken?: string;
  apiKey?: string;
  endpoint?: string;
  service?: string;
  region?: string;
  projectId?: string;
};

type GooglePollState =
  | { family: "veo"; model: string; operationName: string }
  | { family: "interaction"; interactionId: string };

function record(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function strings(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter(
        (entry): entry is string =>
          typeof entry === "string" && entry.length > 0,
      )
    : [];
}

function stringValue(
  values: Record<string, unknown>,
  params: Record<string, unknown>,
  key: string,
): string | undefined {
  const value = params[key] ?? values[key];
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

async function credentialsFor(
  context: ExecutorContext,
): Promise<GoogleCredentials> {
  const accessToken = await context.store?.get("accessToken");
  const apiKey = accessToken ? undefined : await context.store?.get("apiKey");
  if (!accessToken && !apiKey) return {};
  const keys = ["endpoint", "service", "region", "projectId"] as const;
  const stored = await Promise.all(
    keys.map(async (key) => [key, await context.store?.get(key)] as const),
  );
  return {
    ...(accessToken ? { accessToken } : { apiKey: apiKey! }),
    ...Object.fromEntries(
      stored.filter(
        (entry): entry is readonly [(typeof keys)[number], string] =>
          typeof entry[1] === "string" && entry[1].length > 0,
      ),
    ),
  };
}

/** Which path shape this host uses. Decided by the host, which the account chose. */
/** A stored key, shaped for spreading: absent stays absent rather than becoming `undefined`. */
async function storedField(
  context: { store?: { get(key: string): Promise<string | undefined> } },
  key: string,
): Promise<Record<string, string>> {
  const value = await context.store?.get(key);
  return value ? { [key]: value } : {};
}

async function readJson(response: {
  ok: boolean;
  status: number;
  statusText: string;
  text(): Promise<string>;
}): Promise<Record<string, unknown>> {
  const raw = await response.text();
  try {
    const parsed: unknown = JSON.parse(raw);
    return parsed && typeof parsed === "object"
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    // A proxy or a quota page answers with HTML, and folding that into an empty object loses the
    // only explanation there was.
    throw new Error(
      `Google returned a non-JSON response (${response.status}): ${raw.slice(0, 200)}`,
    );
  }
}

interface InlinePart {
  inlineData?: { mimeType?: unknown; data?: unknown };
  inline_data?: { mimeType?: unknown; mime_type?: unknown; data?: unknown };
  text?: unknown;
}

/**
 * Finds the generated bytes.
 *
 * Both spellings occur — `inlineData` on one surface and `inline_data` on the other — so this reads
 * either rather than trusting one.
 */
function firstInlineMedia(
  body: Record<string, unknown>,
): { data: string; mimeType: string } | undefined {
  const candidates = body.candidates;
  if (!Array.isArray(candidates)) return undefined;
  for (const candidate of candidates) {
    const content = (candidate as { content?: { parts?: unknown } }).content;
    const parts = content?.parts;
    if (!Array.isArray(parts)) continue;
    for (const part of parts as InlinePart[]) {
      const inline = part.inlineData ?? part.inline_data;
      if (!inline) continue;
      const data = inline.data;
      const mime =
        (inline as { mimeType?: unknown }).mimeType ??
        (inline as { mime_type?: unknown }).mime_type;
      if (typeof data === "string" && data) {
        return {
          data,
          mimeType: typeof mime === "string" && mime ? mime : "image/png",
        };
      }
    }
  }
  return undefined;
}

/** The model's words, for a text generation. */
function firstText(body: Record<string, unknown>): string | undefined {
  const candidates = body.candidates;
  if (!Array.isArray(candidates)) return undefined;
  for (const candidate of candidates) {
    const parts = (candidate as { content?: { parts?: unknown } }).content
      ?.parts;
    if (!Array.isArray(parts)) continue;
    for (const part of parts as InlinePart[]) {
      if (typeof part.text === "string" && part.text) return part.text;
    }
  }
  return undefined;
}

/**
 * The ratio to send. Two kinds arrive here, not three.
 *
 * `custom` is a declaration -- it says the model accepts shapes outside its listed menu -- and never
 * arrives as a value. What arrives is either `auto`, meaning the model decides, or a concrete ratio.
 * Sending the literal word would earn a proto-enum error that explains nothing to whoever chose it.
 *
 * A concrete ratio is sent as asked. Google keeps a closed set and refuses the rest -- measured: 16:9
 * returns 1376x768, while 7:3 and 5:7 are both "Request contains an invalid argument" -- and that
 * refusal is the honest answer. Rounding to the nearest listed shape would bill the caller for a
 * picture they did not choose.
 */
function resolveRatio(
  ratio: string | undefined,
  values: Record<string, unknown>,
): string | undefined {
  const width = Number(values.aspectRatioWidth);
  const height = Number(values.aspectRatioHeight);
  const hasPair =
    Number.isInteger(width) &&
    Number.isInteger(height) &&
    width > 0 &&
    height > 0;
  if (hasPair) return aspectRatioLabel({ width, height });
  if (!ratio || ratio === "auto" || ratio === "adaptive" || ratio === "custom")
    return undefined;
  return ratio;
}

/**
 * Google's request body, built here because the envelope is the per-vendor part.
 *
 * The catalogue's ratio arrives as written -- "16:9", "1:1", and also "adaptive"/"auto", which are
 * not ratios but "you decide". Google has no spelling for that, so the field is left out instead of
 * being filled with a shape the caller did not choose.
 */
function dataPart(
  url: string,
  fallbackMimeType: string,
): Record<string, unknown> {
  const match = /^data:([^;,]+)(?:;[^,]*)?;base64,([\s\S]+)$/i.exec(url);
  if (match) {
    return {
      inlineData: { mimeType: match[1] || fallbackMimeType, data: match[2] },
    };
  }
  return { fileData: { mimeType: fallbackMimeType, fileUri: url } };
}

function orderedParts(
  values: Record<string, unknown>,
): Record<string, unknown>[] {
  const ordered = values.orderedContentParts;
  if (Array.isArray(ordered) && ordered.length > 0) {
    return ordered.flatMap((entry): Record<string, unknown>[] => {
      const part = record(entry);
      if (part.type === "text" && typeof part.text === "string")
        return [{ text: part.text }];
      if (typeof part.url !== "string") return [];
      if (part.type === "image") return [dataPart(part.url, "image/png")];
      if (part.type === "video") return [dataPart(part.url, "video/mp4")];
      if (part.type === "audio") return [dataPart(part.url, "audio/wav")];
      return [];
    });
  }
  const prompt = typeof values.prompt === "string" ? values.prompt : "";
  return [
    ...(prompt ? [{ text: prompt }] : []),
    ...strings(values.referenceImageUrls).map((url) =>
      dataPart(url, "image/png"),
    ),
    ...strings(values.referenceVideoUrls).map((url) =>
      dataPart(url, "video/mp4"),
    ),
    ...strings(values.referenceAudioUrls).map((url) =>
      dataPart(url, "audio/wav"),
    ),
  ];
}

function generateContentBody(
  values: Record<string, unknown>,
): Record<string, unknown> {
  const explicit = values.body;
  if (explicit && typeof explicit === "object")
    return explicit as Record<string, unknown>;

  const kind = typeof values.kind === "string" ? values.kind : "image";
  const params = record(values.modelParams);
  const ratio =
    typeof values.aspectRatio === "string" ? values.aspectRatio : undefined;
  const size = stringValue(values, params, "resolution");
  const chosenRatio = resolveRatio(ratio, values);

  const imageConfig: Record<string, unknown> = {
    ...(chosenRatio ? { aspectRatio: chosenRatio } : {}),
    ...(size ? { imageSize: size } : {}),
  };
  const responseModalities =
    kind === "audio"
      ? ["AUDIO"]
      : kind === "text"
        ? ["TEXT"]
        : ["TEXT", "IMAGE"];
  const voiceName = stringValue(values, params, "voice_name") ?? "Kore";
  const systemPrompt = stringValue(values, params, "system_prompt");
  return {
    // Agent Platform rejects a content without a role; the Developer API defaults it. One provider
    // serves both, so the stricter of the two sets the shape.
    ...(systemPrompt
      ? { systemInstruction: { parts: [{ text: systemPrompt }] } }
      : {}),
    contents: [{ role: "user", parts: orderedParts(values) }],
    generationConfig: {
      responseModalities,
      ...(kind === "image" && Object.keys(imageConfig).length
        ? { imageConfig }
        : {}),
      ...(kind === "audio"
        ? {
            speechConfig: {
              voiceConfig: { prebuiltVoiceConfig: { voiceName } },
            },
          }
        : {}),
    },
  };
}

function veoImage(url: string): Record<string, unknown> {
  const part = dataPart(url, "image/png");
  const inline = record(part.inlineData);
  if (typeof inline.data === "string") {
    return {
      bytesBase64Encoded: inline.data,
      mimeType:
        typeof inline.mimeType === "string" ? inline.mimeType : "image/png",
    };
  }
  const file = record(part.fileData);
  return {
    gcsUri: file.fileUri,
    mimeType: typeof file.mimeType === "string" ? file.mimeType : "image/png",
  };
}

function veoBody(values: Record<string, unknown>): Record<string, unknown> {
  const params = record(values.modelParams);
  const prompt = typeof values.prompt === "string" ? values.prompt : "";
  const start =
    typeof values.startFrameUrl === "string" ? values.startFrameUrl : undefined;
  const end =
    typeof values.endFrameUrl === "string" ? values.endFrameUrl : undefined;
  const references = strings(values.referenceImageUrls);
  const duration = Number(params.duration ?? values.duration ?? 4);
  return {
    instances: [
      {
        prompt,
        ...(start ? { image: veoImage(start) } : {}),
        ...(end ? { lastFrame: veoImage(end) } : {}),
        ...(references.length
          ? {
              referenceImages: references.map((url) => ({
                image: veoImage(url),
                referenceType: "asset",
              })),
            }
          : {}),
      },
    ],
    parameters: {
      aspectRatio: String(params.aspect_ratio ?? values.aspectRatio ?? "16:9"),
      durationSeconds: Number.isFinite(duration) ? duration : 4,
      generateAudio: params.generate_audio !== false,
      sampleCount: 1,
    },
  };
}

function interactionBody(
  values: Record<string, unknown>,
  model: string,
): Record<string, unknown> {
  const params = record(values.modelParams);
  const duration = Number(params.duration ?? values.duration ?? 5);
  return {
    model,
    input: typeof values.prompt === "string" ? values.prompt : "",
    response_format: {
      type: "video",
      aspect_ratio: String(params.aspect_ratio ?? values.aspectRatio ?? "16:9"),
      duration: `${Number.isFinite(duration) ? duration : 5}s`,
    },
    background: true,
    store: true,
    stream: false,
  };
}

function googleAuthHeaders(
  credentials: GoogleCredentials,
): Record<string, string> {
  if (credentials.accessToken) {
    return {
      Authorization: `Bearer ${credentials.accessToken}`,
      "content-type": "application/json",
    };
  }
  if (credentials.apiKey) {
    return {
      "x-goog-api-key": credentials.apiKey,
      "content-type": "application/json",
    };
  }
  throw new Error(
    "This Google account has neither an accessToken nor an apiKey stored.",
  );
}

function agentPlatformPrefix(
  baseUrl: string,
  credentials: GoogleCredentials,
  version = "v1",
): string {
  if (!credentials.projectId) {
    throw new Error(
      "This Agent Platform account has no project id; it comes from the service account key.",
    );
  }
  const location = credentials.region || "global";
  const origin = baseUrl.replace(/\/v1(?:beta1)?\/?$/, "");
  return `${origin}/${version}/projects/${credentials.projectId}/locations/${location}`;
}

function veoPath(
  baseUrl: string,
  credentials: GoogleCredentials,
  model: string,
  operation: string,
): string {
  return `${agentPlatformPrefix(baseUrl, credentials)}/publishers/google/models/${encodeURIComponent(model)}:${operation}`;
}

function interactionPath(
  baseUrl: string,
  credentials: GoogleCredentials,
  interactionId?: string,
): string {
  const trimmed = baseUrl.replace(/\/+$/, "");
  if (!/aiplatform\.googleapis\.com/.test(trimmed)) {
    if (!interactionId) return `${trimmed}/interactions`;
    const path = interactionId.replace(/^\/+/, "");
    return `${trimmed}/${path.startsWith("interactions/") ? path : `interactions/${path}`}`;
  }
  if (interactionId?.startsWith("projects/")) {
    const origin = trimmed.replace(/\/v1(?:beta1)?\/?$/, "");
    return `${origin}/v1beta1/${interactionId}`;
  }
  const prefix = agentPlatformPrefix(baseUrl, credentials, "v1beta1");
  return `${prefix}/interactions${interactionId ? `/${interactionId.replace(/^interactions\//, "")}` : ""}`;
}

function pollState(value: unknown): GooglePollState {
  const state = record(value);
  if (
    state.family === "veo" &&
    typeof state.model === "string" &&
    typeof state.operationName === "string"
  ) {
    return {
      family: "veo",
      model: state.model,
      operationName: state.operationName,
    };
  }
  if (
    state.family === "interaction" &&
    typeof state.interactionId === "string"
  ) {
    return { family: "interaction", interactionId: state.interactionId };
  }
  throw new Error("Google poll state is missing or invalid.");
}

function mediaFromUnknown(
  value: unknown,
): { data?: string; url?: string; mimeType: string } | undefined {
  if (!value || typeof value !== "object") return undefined;
  if (Array.isArray(value)) {
    for (const entry of value) {
      const media = mediaFromUnknown(entry);
      if (media) return media;
    }
    return undefined;
  }
  const object = value as Record<string, unknown>;
  const inline = record(object.inlineData ?? object.inline_data);
  const inlineData = inline.data;
  if (typeof inlineData === "string" && inlineData) {
    const mime = inline.mimeType ?? inline.mime_type;
    return {
      data: inlineData,
      mimeType: typeof mime === "string" ? mime : "application/octet-stream",
    };
  }
  const data = object.bytesBase64Encoded ?? object.bytesBase64 ?? object.data;
  const mime = object.mimeType ?? object.mime_type;
  if (typeof data === "string" && data && typeof mime === "string") {
    return { data, mimeType: mime };
  }
  const url = object.gcsUri ?? object.uri ?? object.url;
  if (
    typeof url === "string" &&
    url &&
    (typeof mime === "string" || /^gs:|^https?:/.test(url))
  ) {
    return { url, mimeType: typeof mime === "string" ? mime : "video/mp4" };
  }
  for (const child of Object.values(object)) {
    const media = mediaFromUnknown(child);
    if (media) return media;
  }
  return undefined;
}

function mediaStep(media: {
  data?: string;
  url?: string;
  mimeType: string;
}): ExecutorStep {
  return {
    status: "completed",
    media: {
      media: media.data
        ? { base64: media.data, mediaType: media.mimeType }
        : { url: media.url!, mediaType: media.mimeType },
    },
  };
}

/**
 * What a Google account needs, declared for the host to render.
 *
 * Four credentials across two surfaces, and which one works depends on the surface -- measured, not
 * guessed. An api key answers on the Developer API and returns 401 "API keys are not supported by
 * this API" on Agent Platform, so `service` is not cosmetic: it decides which host is addressed and
 * therefore which credential is the right one.
 *
 * `region` has a default because one exists that works; `apiKey` does not, because an account
 * without a credential does not work at all.
 */
// `satisfies`, so the declaration is checked against the schema's type while keeping the literal
// shape the schema wants: `options` is declared non-empty, which is a tuple, and a plain array
// annotation widens it back to something the schema rejects.
const REGION_FIELD = {
  kind: "choice",
  key: "region",
  label: "Region",
  options: [
    { value: "global", label: "Global" },
    { value: "us-central1", label: "us-central1" },
  ],
  // Measured: gemini-3.1-flash-image answers on global and 404s on us-central1.
  default: "global",
} satisfies PluginAuthFormItem;

export const GOOGLE_AUTH: PluginAuthDeclaration = {
  /**
   * Three coherent configurations, each complete on its own.
   *
   * Google has two surfaces and two credentials, and they do not pair off evenly. A service account
   * signs an RFC 7523 assertion that only Agent Platform accepts. An API key works on both: AI
   * Studio directly, Agent Platform in Express mode. And a region is an Agent Platform concept --
   * AI Studio has none.
   *
   * As a single form this needed a `service` choice plus a condition hiding it once a service
   * account was pasted, and before that a notice claiming Agent Platform refuses API keys, which is
   * simply false. As methods, each carries exactly the fields its configuration needs: `region` is
   * absent from the AI Studio method rather than present and ignored, because a field that is
   * present and ignored teaches the reader that fields can be ignored.
   */
  methods: [
    {
      id: "ai-studio",
      label: "Google AI Studio (Developer API)",
      form: [
        {
          kind: "notice" as const,
          text: "Create a key at aistudio.google.com/apikey.",
        },
        {
          kind: "field" as const,
          key: "apiKey",
          label: "API key",
          secret: true,
        },
      ],
    },
    {
      id: "agent-platform-key",
      label: "Google Cloud Agent Platform (API key)",
      form: [
        {
          kind: "notice" as const,
          text: "Agent Platform accepts an API key in Express mode.",
        },
        {
          kind: "field" as const,
          key: "apiKey",
          label: "API key",
          secret: true,
        },
        REGION_FIELD,
      ],
    },
    {
      id: "service-account",
      label: "Google Cloud Agent Platform (service account)",
      form: [
        {
          kind: "notice" as const,
          text:
            "Paste the JSON key file. It is exchanged for an access token via RFC 7523; the " +
            "assertion is signed locally and the key itself is never sent.",
        },
        {
          kind: "field" as const,
          key: "serviceAccountKey",
          label: "Service account JSON",
          secret: true,
        },
        REGION_FIELD,
      ],
    },
  ],
};

/**
 * Which Google surface this account addresses.
 *
 * Asymmetric, because the two credentials are. A service account signs an RFC 7523 assertion that
 * only Agent Platform accepts, so holding one settles the question whatever the stored choice says
 * -- and a store can hold a stale `service` from before the key was pasted. An API key works on
 * both surfaces, AI Studio directly and Agent Platform in Express mode, so it settles nothing and
 * the account's own choice decides.
 */
export function googleServiceFor(stored: {
  apiKey?: string;
  serviceAccountKey?: string;
  service?: string;
}): "ai-studio" | "agent-platform" {
  if (stored.serviceAccountKey?.trim()) return "agent-platform";
  if (!stored.apiKey?.trim()) {
    throw new Error(
      "This Google account holds neither apiKey nor serviceAccountKey, so there is no surface to address.",
    );
  }
  return stored.service === "agent-platform" ? "agent-platform" : "ai-studio";
}

export const googleAdapter: ProviderExecutor = {
  async submit(
    invocation: ExecutablePluginInvocation,
    context: ExecutorContext,
  ): Promise<ExecutorStep> {
    const credentials = await credentialsFor(context);
    const headers = googleAuthHeaders(credentials);
    const fetchImpl = globalThis.fetch as unknown as FetchLike;
    const baseUrl = googleBaseUrl({
      ...(credentials.endpoint ? { endpoint: credentials.endpoint } : {}),
      ...(credentials.service ? { service: credentials.service } : {}),
      ...(credentials.region ? { region: credentials.region } : {}),
      hasServiceAccount: Boolean(credentials.projectId),
    });
    const values = invocation.input.values;
    const model = String(values.upstreamModel ?? values.model ?? "");
    if (!model) throw new Error("Google executor needs a model.");

    const modelId = String(values.modelId ?? "");
    const kind = String(values.kind ?? "image");
    const interaction =
      values.apiShape === "google-ai-studio-interactions" ||
      modelId === "gemini-omni-flash";
    const veo =
      kind === "video" &&
      (modelId.startsWith("veo-") || model.startsWith("veo-"));
    const url = interaction
      ? interactionPath(baseUrl, credentials)
      : veo
        ? veoPath(baseUrl, credentials, model, "predictLongRunning")
        : googleModelPath({
            baseUrl,
            model,
            ...(credentials.projectId
              ? { projectId: credentials.projectId }
              : {}),
            ...(credentials.region ? { location: credentials.region } : {}),
          });
    const request = interaction
      ? interactionBody(values, model)
      : veo
        ? veoBody(values)
        : generateContentBody(values);
    const response = await fetchImpl(url, {
      method: "POST",
      headers,
      body: JSON.stringify(request),
    });
    const body = await readJson(response);
    if (!response.ok) {
      const error = (body.error as { message?: unknown } | undefined)?.message;
      throw new Error(
        `Google ${interaction ? "Interactions" : veo ? "Veo" : "generateContent"} failed: ` +
          `${typeof error === "string" ? error : response.statusText}`,
      );
    }

    if (veo) {
      const operationName = body.name;
      if (typeof operationName !== "string" || !operationName) {
        throw new Error(`Google Veo returned no operation name for ${model}.`);
      }
      return {
        status: "accepted",
        pollState: { family: "veo", model, operationName },
      };
    }

    if (interaction) {
      const media = mediaFromUnknown(body.outputs ?? body.output ?? body);
      if (media) return mediaStep(media);
      const status = body.status;
      const interactionId = body.id ?? body.name;
      if (
        (status === "pending" ||
          status === "in_progress" ||
          status === "running") &&
        typeof interactionId === "string"
      ) {
        return {
          status: "accepted",
          pollState: { family: "interaction", interactionId },
        };
      }
      throw new Error(`Google Interactions returned no media for ${model}.`);
    }

    const media = firstInlineMedia(body);
    if (media) {
      // Returned as data, not uploaded here. Google answers with base64, so that is what this
      // hands back; the SDK decodes and stores it.
      return {
        status: "completed",
        media: { media: { base64: media.data, mediaType: media.mimeType } },
      };
    }
    const text = firstText(body);
    if (text)
      return { status: "completed", outputs: valueOutput(text, "text") };

    // Finished with nothing in it is not a result. Reporting completion here would attach an empty
    // asset and close the task as though it had worked.
    throw new Error(`Google returned no media or text for ${model}.`);
  },

  async poll(
    invocation: ExecutablePluginInvocation,
    context: ExecutorContext,
  ): Promise<ExecutorStep> {
    const state = pollState(invocation.pollState);
    const credentials = await credentialsFor(context);
    const headers = googleAuthHeaders(credentials);
    const baseUrl = googleBaseUrl({
      ...(credentials.endpoint ? { endpoint: credentials.endpoint } : {}),
      ...(credentials.service ? { service: credentials.service } : {}),
      ...(credentials.region ? { region: credentials.region } : {}),
      hasServiceAccount: Boolean(credentials.projectId),
    });
    const fetchImpl = globalThis.fetch as unknown as FetchLike;
    const response =
      state.family === "veo"
        ? await fetchImpl(
            veoPath(baseUrl, credentials, state.model, "fetchPredictOperation"),
            {
              method: "POST",
              headers,
              body: JSON.stringify({ operationName: state.operationName }),
            },
          )
        : await fetchImpl(
            interactionPath(baseUrl, credentials, state.interactionId),
            {
              method: "GET",
              headers,
            },
          );
    const body = await readJson(response);
    if (!response.ok) {
      const error = (body.error as { message?: unknown } | undefined)?.message;
      throw new Error(
        `Google poll failed: ${typeof error === "string" ? error : response.statusText}`,
      );
    }
    const media = mediaFromUnknown(
      body.response ?? body.outputs ?? body.output ?? body,
    );
    if (media) return mediaStep(media);
    if (
      body.done === true ||
      body.status === "failed" ||
      body.status === "cancelled"
    ) {
      const error = record(body.error).message;
      throw new Error(
        `Google generation finished without media${typeof error === "string" ? `: ${error}` : "."}`,
      );
    }
    return { status: "accepted", pollState: state };
  },
};
